
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Nunito } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const nunito = Nunito({
  subsets: ['latin'],
  variable: '--font-nunito',
});


export const metadata: Metadata = {
  title: 'ChirpChat',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${nunito.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}

